name: e2e-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dashboard-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    container:
      image: cypress/browsers
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies with pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.1

      - name: Install Packages
        run: pnpm install

      - name: Install Cypress
        run: pnpm add cypress --save-dev && pnpm cypress install

      - name: Run E2E Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: http://localhost:3000
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
          PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
        run: pnpm dlx start-server-and-test "pnpm dev" http://localhost:3000 "pnpm cypress run"
  build:
    needs: dashboard-e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies with pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.1

      - name: Install Packages
        run: pnpm install
      - name: Get Build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: http://localhost:3000
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
        run: pnpm build
