name: e2e-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    container:
      image: cypress/browsers
    steps:
      - name: Get Code
        uses: actions/checkout@v6

      - name: Install Dependencies with pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.1

      - name: Install Packages
        run: pnpm install

      - name: Get Build
        run: pnpm build

      - name: Install Cypress
        run: pnpm add cypress --save-dev && pnpm cypress install

      - name: Run E2E Tests
        run: pnpm dlx start-server-and-test "pnpm start" http://localhost:3000 "pnpm cypress run"
