name: e2e-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dashboard-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    container:
      image: cypress/browsers
    steps:
      - name: Get Code
        uses: actions/checkout@v6

      - name: Install Dependencies with pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.1

      - name: Install Packages
        run: pnpm install

      - name: Get Build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: http://localhost:3000
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: pnpm build

      - name: Install Cypress
        run: pnpm add cypress --save-dev && pnpm cypress install

      - name: Run E2E Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: http://localhost:3000
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: pnpm dlx start-server-and-test "pnpm start" http://localhost:3000 "pnpm cypress run"
